---
name: Lint Code Base

"on":
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  Lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          YAML_ERROR_ON_WARNING: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
